---
- name: Remove root user
  mysql_user:
    name: root
    host_all: yes
    state: absent
    login_user: '{{admin_users.name}}'
    login_password: '{{admin_users.pass}}'
    login_unix_socket: /var/run/mysqld/mysqld.sock